# The name of the action
name: Django tests
# The name of the action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# What to do when the action is triggered
jobs:
  # A job called 'build' - arbitrary
  build:
    # Run on a Ubuntu VM
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the GitHub repo
    - uses: actions/checkout@v3
    
    # Install Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    # Pip install project dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # check mistakes by flake8
    - name: Check mistakes
      run: |
        python -m flake8
